### ISSUE TITLE
怎么编译啊。

### ISSUE THREAD

**Issue by yanchaoGan** [CUITCHE/code-obfuscation#1]
编译报错，，mac teamid 没有。

能否发一个release的，直接包含 ./code0bfuscation  可执行文件的

**Comment by wzhejunqiu** [comment]
好的，一直没有发布release的，就是我还没测试完成，预计这个周末就会出release的。
关于team id的问题，你可以修改成你自己的账号。
[这儿有生成好的beta版，你可以试试](https://github.com/CUITCHE/code-obfuscation/blob/master/CodeObfuscation/CodeObfuscation/CodeObfuscation)

**Comment by wzhejunqiu** [comment]
Commit #bc4dfe56dfbb808e0577262c8f62b32f720b940e has contained executable program. See release tag 0.0.1
